import { expect, test, type Page } from '@playwright/test'
test.use({ actionTimeout: 10000 })

const reference = (page: Page, input: Record<string, unknown>) => page.evaluate(input => (window as any).lense.call('osrs_reference', input), input)

test('OSRS guide exposes bounded read-only lookups, deep links and a prompt draft', async ({ page }) => {
  const localRequests: string[] = [], errors: string[] = []
  page.on('request', request => { if (/127\.0\.0\.1:1737[345]/.test(request.url())) localRequests.push(request.url()) })
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/osrs?entry=place-lumbridge-bank')
  await expect.poll(() => page.evaluate(() => (window as any).lense?.tools.map((tool: any) => tool.name))).toEqual(['osrs_reference'])
  await expect(page.getByRole('heading', { name: 'Lumbridge Castle bank', exact: true })).toBeVisible()
  await page.screenshot({ path: 'artifacts/osrs-local-map.png', fullPage: true })
  await page.getByLabel('Search map', { exact: true }).fill('Draynor')
  await page.getByRole('combobox', { name: 'Filter map', exact: true }).selectOption('bank')
  await expect(page.locator('[data-map-marker].town')).toHaveCount(0)
  await expect(page.locator('[data-map-marker].resource')).toHaveCount(0)
  await page.getByRole('button', { name: 'Draynor bank, bank', exact: true }).click()
  await expect(page.locator('#osrs-entry-detail').getByRole('heading', { name: 'Draynor bank', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Zoom out', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Reset map view', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Zoom out', exact: true })).toBeDisabled()
  const first = await reference(page, { operation: 'search', kind: 'visual', query: 'bank', limit: 1 })
  expect(first.items).toHaveLength(1)
  expect(first.items[0].kind).toBe('visual')
  expect(first.nextOffset).toBe(1)
  const second = await reference(page, { operation: 'search', kind: 'visual', query: 'bank', limit: 1, offset: 1 })
  expect(second.items[0].id).not.toBe(first.items[0].id)
  const detail = await reference(page, { operation: 'get', id: 'visual-banker' })
  expect(detail.visual.confusions).toContain('A deposit box')
  expect(detail.sourceUrls).toContain('https://oldschool.runescape.wiki/w/Bank')
  expect(detail).not.toHaveProperty('content')
  const invalid = await reference(page, { operation: 'start', config: { goal: 'must not run' } })
  expect(invalid.isError).toBe(true)
  expect(localRequests).toEqual([])
  await page.goto('/osrs?entry=prompt-lumbridge-trees')
  await page.getByRole('link', { name: 'Use this prompt', exact: true }).click()
  await expect(page).toHaveURL(/osrsPrompt=prompt-lumbridge-trees/)
  await expect(page.getByLabel('Task goal')).toHaveValue(/up to five currently visible normal trees/)
  await expect(page.getByLabel('Until complete', { exact: true })).toBeChecked()
  await expect(page.getByLabel('Application or game')).toHaveValue('osrs')
  const state = await page.evaluate(() => (window as any).lense.call('desktop_status'))
  expect(state.task).toBeNull()
  expect(state.queue.items).toHaveLength(0)
  expect(state.paired).toBe(false)
  expect(errors).toEqual([])
})

test('saved screenshot examples persist locally and are returned only on explicit image lookup', async ({ page }) => {
  await page.goto('/osrs?entry=visual-banker')
  await expect(page.locator('#osrs-entry-detail').getByRole('heading', { name: 'Banker or bank booth', exact: true })).toBeVisible()
  const encoded = await page.evaluate(() => {
    const canvas = document.createElement('canvas'); canvas.width = 32; canvas.height = 32
    const context = canvas.getContext('2d')!; context.fillStyle = '#245d3f'; context.fillRect(0, 0, 32, 32)
    return canvas.toDataURL('image/png').split(',')[1]!
  })
  const upload = page.locator('input[type=file]')
  await page.getByText('Your screenshot examples', { exact: true }).click()
  await upload.setInputFiles({ name: 'test-bank-crop.png', mimeType: 'image/png', buffer: Buffer.from(encoded, 'base64') })
  await expect.poll(async () => {
    const result = await reference(page, { operation: 'get', id: 'visual-banker', includeImages: true })
    return result.content?.filter((part: any) => part.type === 'image').length
  }).toBe(1)
  expect((await reference(page, { operation: 'get', id: 'visual-banker' })).content).toBeUndefined()
  await page.reload()
  await expect.poll(() => page.evaluate(() => !!(window as any).lense)).toBe(true)
  const saved = await reference(page, { operation: 'get', id: 'visual-banker', includeImages: true })
  expect(saved.content.filter((part: any) => part.type === 'image')).toEqual([{ type: 'image', mimeType: 'image/png', data: encoded }])
  await page.getByText('Your screenshot examples', { exact: true }).click()
  await page.getByRole('button', { name: /Remove.*example/ }).click()
  await expect.poll(async () => (await reference(page, { operation: 'get', id: 'visual-banker', includeImages: true })).content.filter((part: any) => part.type === 'image').length).toBe(0)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: 'artifacts/osrs-local-mobile.png', fullPage: true })
  await page.goto('/osrs?section=map')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
})
