const number = {type:'number', minimum:0, maximum:1}
const point = {type:'object',properties:{x:number,y:number},required:['x','y'],additionalProperties:false}
export const targetSchema = {type:'object',properties:{type:{enum:['monitor','window']},id:{type:'string',minLength:1,maxLength:128}},required:['type','id'],additionalProperties:false}
export const regionSchema = {type:'object',properties:{x:number,y:number,width:number,height:number},required:['x','y','width','height'],additionalProperties:false}
function action(type:string, properties:Record<string,unknown>, required:string[]) {return {type:'object',properties:{type:{const:type},...properties},required:['type',...required],additionalProperties:false}}
export const actionSchema = {oneOf:[
  action('pointer.move',{x:number,y:number,target:targetSchema},['x','y']),
  ...['pointer.click','pointer.doubleClick'].map(type=>action(type,{x:number,y:number,button:{enum:['left','right','middle']},target:targetSchema},['x','y'])),
  action('pointer.drag',{from:point,to:point,durationMs:{type:'integer',minimum:50,maximum:5000},target:targetSchema},['from','to','durationMs']),
  action('keyboard.type',{text:{type:'string',minLength:1,maxLength:10000}},['text']),
  action('keyboard.key',{key:{type:'string',minLength:1,maxLength:32}},['key']),
  action('keyboard.hotkey',{keys:{type:'array',items:{type:'string',maxLength:32},minItems:1,maxItems:5}},['keys']),
  action('scroll',{deltaX:{type:'integer',minimum:-10000,maximum:10000},deltaY:{type:'integer',minimum:-10000,maximum:10000}},['deltaX','deltaY']),
  action('window.focus',{windowId:{type:'string',minLength:1,maxLength:128}},['windowId']),
]}
export const agentActionSchema = { oneOf: actionSchema.oneOf.map(schema => ({ ...schema, properties: { ...schema.properties, expectedTaskId: { type: 'string', minLength: 1, maxLength: 128 }, observationId: { type: 'string', minLength: 1, maxLength: 128 }, observeAfter: {type:'boolean'}, settleMs: {type:'integer',minimum:0,maximum:2000} } })) }
export const captureSchema = {type:'object',properties:{source:{enum:['native','browser'],description:'Default is the source shown in the preview. Native captures provide input coordinates; browser shares are observation only.'},target:targetSchema,region:regionSchema,maxDimension:{type:'integer',minimum:160,maximum:2560},quality:{type:'number',minimum:0.1,maximum:1}},additionalProperties:false}
export const taskContextSchema = { type: 'object', properties: { game: { enum: ['generic', 'osrs', 'rs3'] }, characterName: { type: 'string', maxLength: 120 }, location: { type: 'string', maxLength: 240 }, skills: { type: 'string', maxLength: 2000 }, inventory: { type: 'string', maxLength: 2000 }, notes: { type: 'string', maxLength: 4000 } }, required: ['game'], additionalProperties: false }
export const taskConfigSchema = {type:'object',properties:{goal:{type:'string',minLength:1,maxLength:4000},durationMs:{type:'integer',minimum:1000,maximum:86400000},runMode:{enum:['timed','until-complete','continuous']},completionCondition:{type:'string',minLength:1,maxLength:2000},monitoring:{type:'object',properties:{mode:{enum:['interval','events-and-interval']},watchIntervalMs:{type:'integer',minimum:500,maximum:60000},settleMs:{type:'integer',minimum:0,maximum:5000}},required:['mode','watchIntervalMs','settleMs'],additionalProperties:false},context:taskContextSchema,verification:{type:'object',properties:{condition:{type:'string',minLength:1,maxLength:2000},intervalMs:{type:'integer',minimum:500,maximum:3600000}},required:['condition','intervalMs'],additionalProperties:false},invariants:{type:'array',items:{type:'string',maxLength:1000},maxItems:20},limits:{type:'object',properties:{maxConsecutiveFailures:{type:'integer',minimum:1,maximum:20},maxActionsPerMinute:{type:'integer',minimum:1,maximum:120},confidenceThreshold:{type:'number',minimum:0.5,maximum:1}},required:['maxConsecutiveFailures','maxActionsPerMinute','confidenceThreshold'],additionalProperties:false},deadline:{type:'string',format:'date-time'}},required:['goal','durationMs','verification','invariants','limits'],additionalProperties:false}
export const taskOperationSchema = { type: 'object', properties: {
  operation: { enum: ['start','pause','resume','stop','query','enqueue','queue','run-queue','pause-queue','remove-queued','clear-queue','set-repeat','signal','wait','context','complete','cadence'] },
  config: taskConfigSchema, context: taskContextSchema,
  taskId: { type: 'string', minLength: 1, maxLength: 128 }, id: { type: 'string', minLength: 1, maxLength: 128 }, observationId: { type: 'string', minLength: 1, maxLength: 128 },
  message: { type: 'string', minLength: 1, maxLength: 2000 }, eventType: { type: 'string', minLength: 1, maxLength: 80 }, reason: { type: 'string', minLength: 1, maxLength: 2000 },
  afterSequence: { type: 'integer', minimum: 0 }, timeoutMs: { type: 'integer', minimum: 0, maximum: 60000 }, intervalMs: { type: 'integer', minimum: 500, maximum: 3600000 }, repeat: { type: 'boolean' },
}, required: ['operation'], additionalProperties: false }
export const watchSchema = {type:'object',properties:{operation:{enum:['create','remove','query']},watch:{type:'object',properties:{id:{type:'string',minLength:1,maxLength:64},target:targetSchema,region:regionSchema,intervalMs:{type:'integer',minimum:500,maximum:3600000},mode:{const:'visual-change'},threshold:number},required:['id','intervalMs','mode','threshold'],additionalProperties:false},id:{type:'string',minLength:1,maxLength:64}},required:['operation'],additionalProperties:false}
