<script setup lang="ts">
import { Cable, Check, Download, ExternalLink, Monitor, RefreshCw, Shield, Unplug } from 'lucide-vue-next'
import { BRIDGE_DOWNLOAD_PAUSED, BRIDGE_DOWNLOAD_STATUS_URL, BRIDGE_DOWNLOAD_URL } from '../services/bridge/release'
import type { BridgeStatus, DesktopWindow, Monitor as DisplayMonitor, Session, Target } from '../types/protocol'
defineProps<{ status: BridgeStatus | null; session: Session | null; permission: string; error: string; connecting: boolean; monitors: DisplayMonitor[]; windows: DesktopWindow[]; target: Target | null }>()
const emit = defineEmits<{ detect: []; pair: []; unpair: []; target: [target: Target]; refresh: [] }>()
function selectTarget(event: Event) {
  const value = (event.target as HTMLSelectElement).value
  const [type, ...id] = value.split(':')
  if ((type === 'monitor' || type === 'window') && id.length) emit('target', { type, id: id.join(':') })
}
</script>

<template>
  <section class="bridge-panel panel">
    <div class="section-heading"><span class="eyebrow">YOUR COMPUTER, CONNECTED</span><Cable :size="17" /></div>
    <div class="bridge-panel-heading"><h2>{{ session ? target ? 'Ready for desktop input.' : 'Choose your app or screen.' : status ? 'Ready to pair.' : BRIDGE_DOWNLOAD_PAUSED ? 'New Windows setup is on hold.' : 'Connect in four steps.' }}</h2><span class="status-pill" :class="{ connected: !!session }"><span class="signal-dot" />{{ session ? 'Paired' : status ? 'Detected' : 'Not detected' }}</span></div>
    <p class="bridge-description">{{ session ? 'Check the captured preview before sending input. Stop control revokes this browser\'s access.' : BRIDGE_DOWNLOAD_PAUSED ? 'Existing bridge controls remain available. The included browser lab works without a Windows download.' : 'Use this website and the bridge on the same Windows computer. Keep the bridge window open while you work.' }}</p>
    <div v-if="BRIDGE_DOWNLOAD_PAUSED" class="bridge-download-notice" role="status"><strong>Windows download 1.0.1 is paused</strong><p>Norton quarantined this release as IDP.Generic. The report is under review. Keep quarantined copies in quarantine.</p><a class="text-button" :href="BRIDGE_DOWNLOAD_STATUS_URL">Read the download status <ExternalLink :size="13" /></a></div>
    <ol class="setup-checklist" aria-label="Desktop setup progress">
      <li :class="{ complete: !!status && !BRIDGE_DOWNLOAD_PAUSED }"><span class="setup-number"><Check v-if="status && !BRIDGE_DOWNLOAD_PAUSED" :size="14" /><template v-else>1</template></span><div><h3>{{ BRIDGE_DOWNLOAD_PAUSED ? 'Check the release status' : 'Install and open' }}</h3><p>{{ BRIDGE_DOWNLOAD_PAUSED ? 'New Windows setup is on hold while the antivirus report is reviewed.' : status ? 'LenseBridge is running on this computer.' : 'Run Windows setup, then open LenseBridge from the Start menu. Keep its window open.' }}</p><a v-if="BRIDGE_DOWNLOAD_PAUSED" class="text-button" :href="BRIDGE_DOWNLOAD_STATUS_URL">Windows download status<ExternalLink :size="13" /></a><a v-else class="text-button" :href="BRIDGE_DOWNLOAD_URL" download><Download :size="13" />{{ status ? 'Download latest setup' : 'Download Windows setup' }}</a></div></li>
      <li :class="{ complete: !!status }"><span class="setup-number"><Check v-if="status" :size="14" /><template v-else>2</template></span><div><h3>Find the local connection</h3><p>{{ status ? 'Bridge found. The connection stays on this computer.' : 'Select Detect bridge. Choose Allow if your browser asks for local network access.' }}</p><button class="button button-small" :disabled="connecting || !!session" @click="emit('detect')"><RefreshCw :size="13" :class="{ spinning: connecting }" />{{ connecting ? 'Connecting...' : 'Detect bridge' }}</button></div></li>
      <li :class="{ complete: !!session }"><span class="setup-number"><Check v-if="session" :size="14" /><template v-else>3</template></span><div><h3>Pair this browser</h3><p>{{ session ? 'You approved this website in the Windows dialog.' : 'Select Pair desktop, then approve this website in the separate Windows permission dialog.' }}</p><button v-if="!session" class="button button-primary button-small" :disabled="!status || connecting" @click="emit('pair')"><Cable :size="13" />Pair desktop</button></div></li>
      <li :class="{ complete: !!session && !!target, 'setup-pending': !session }"><span class="setup-number"><Check v-if="session && target" :size="14" /><template v-else>4</template></span><div><h3>Choose a monitor or app window</h3><p v-if="!session">Pair first to see the screens and open windows on this computer.</p><div v-else class="capture-target"><label for="desktop-target"><Monitor :size="14" />Capture & input target</label><div><select id="desktop-target" :value="target ? `${target.type}:${target.id}` : ''" @change="selectTarget"><option value="" disabled>Select a monitor or window</option><optgroup label="Monitors"><option v-for="monitor in monitors" :key="monitor.id" :value="`monitor:${monitor.id}`">{{ monitor.name }} · {{ monitor.width }} × {{ monitor.height }}{{ monitor.primary ? ' · Primary' : '' }}</option></optgroup><optgroup label="Windows"><option v-for="window in windows" :key="window.id" :value="`window:${window.id}`">{{ window.title }}</option></optgroup></select><button class="icon-button" aria-label="Refresh capture targets" title="Refresh capture targets" @click="emit('refresh')"><RefreshCw :size="15" /></button></div></div><p class="target-explanation">Choose a window for typing, shortcuts, and scrolling. Choose a monitor for screenshots and clicks. Windows uses its normal mouse and keyboard.</p><p v-if="session && target" class="target-ready"><Check :size="13" />Target selected. Check its screenshot in Control.</p></div></li>
    </ol>
    <p v-if="!status && !BRIDGE_DOWNLOAD_PAUSED" class="connection-tip">Already open? Select Detect bridge. A second launch reuses the running bridge. An older companion can stay open.</p>
    <p v-if="permission === 'denied'" class="connection-tip">Local network access is blocked. Open this site's browser permissions, allow local network access, then select Detect bridge again.</p>
    <div v-if="error" class="inline-error" role="status">{{ error }}</div>
    <details class="bridge-connection-details"><summary>Connection details</summary><div class="bridge-meta"><span>Browser network permission <b>{{ permission || 'Not queried' }}</b></span><span>Protocol <b>{{ status ? `v${status.protocolVersion}` : 'Waiting' }}</b></span><span v-if="status?.endpoint">Local connection <b>{{ status.endpoint }}</b></span><span v-if="session">Approved website <b>{{ session.origin }}</b></span></div></details>
    <div class="bridge-security"><Shield :size="14" /><span>Localhost only. Native approval. No shell access.</span><button v-if="session" class="text-button danger-text" @click="emit('unpair')"><Unplug :size="13" />Disconnect</button></div>
  </section>
</template>
