import { chromium, expect } from '@playwright/test'
import { mkdir } from 'node:fs/promises'

await mkdir('artifacts', { recursive: true })
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
const errors = []
page.on('pageerror', error => errors.push(error.message))

try {
  await page.goto(process.env.LENSE_PRODUCTION_URL || 'https://lense-visual-control.netlify.app')
  await page.getByRole('heading', { name: 'Your desktop. Your direction.' }).waitFor()
  const toggle = page.getByRole('button', { name: 'Help for this page', exact: true })
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await toggle.click()
  const guide = page.locator('#page-guide')
  await expect(guide.getByRole('heading', { name: 'Your first run takes 30 seconds.', exact: true })).toBeVisible()
  await toggle.click()
  await expect(guide).toHaveCount(0)
  await toggle.click()
  await page.keyboard.press('Escape')
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(toggle).toBeFocused()
  await toggle.click()

  await page.getByRole('button', { name: 'Windows desktop', exact: true }).click()
  await expect(guide.getByRole('heading', { name: 'Pair, choose a window, then try one action.', exact: true })).toBeVisible()
  await expect(guide.getByRole('heading', { name: 'Which device do I choose?', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Desktop bridge', exact: true }).click()
  await page.getByRole('heading', { name: 'Connect your Windows desktop.', exact: true }).waitFor()
  await expect(guide.getByRole('heading', { name: 'Connect this computer, then choose an app.', exact: true })).toBeVisible()
  await expect(guide.getByRole('link', { name: 'Windows download status', exact: true })).toHaveAttribute('href', '/bridge-download-status.html')
  await expect(page.locator('a[download]')).toHaveCount(0)
  console.log('Bridge navigation and connection guide succeeded')
  await page.getByText('Connection details', { exact: true }).click()
  console.log(await page.locator('.bridge-meta').innerText())

  await page.getByRole('button', { name: 'Demo playbook', exact: true }).click()
  await page.getByRole('heading', { name: 'Put it to work.' }).waitFor()
  await expect(guide.getByRole('heading', { name: 'Try the browser lab, then real desktop input.', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Event history', exact: true }).click()
  await expect(guide.getByRole('heading', { name: 'Review what happened, frame by frame.', exact: true })).toBeVisible()
  console.log('Demo and history guides succeeded')

  await page.setViewportSize({ width: 390, height: 844 })
  await expect(guide).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.getByRole('button', { name: 'Desktop bridge', exact: true }).click()
  await expect(guide.getByRole('heading', { name: 'Which device do I choose?', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: 'artifacts/production-mobile-help.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: 'Control center', exact: true }).first().click()
  await page.getByRole('button', { name: 'Woodcutting lab', exact: false }).click()
  await page.getByRole('button', { name: 'Close page help', exact: true }).click()
  await page.getByLabel('Until stopped', { exact: true }).check()
  await page.getByRole('button', { name: 'Add to queue', exact: true }).click()
  await page.getByRole('button', { name: 'Run queue', exact: true }).click()
  const status = () => page.evaluate(() => window.lense.call('desktop_status'))
  await expect.poll(async () => (await status()).task?.actions).toBeGreaterThan(0)
  expect((await status()).task.runMode).toBe('continuous')
  await page.getByRole('button', { name: 'Pause queue', exact: true }).click()
  await expect.poll(async () => (await status()).task?.state).toBe('PAUSED')
  await expect(page.getByRole('button', { name: 'Run queue', exact: true })).toBeEnabled()
  await page.screenshot({ path: 'artifacts/production-control-center.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: 'artifacts/production-mobile-queue.png', fullPage: true })
  expect(errors).toEqual([])
  console.log(JSON.stringify({ pageErrors: errors, url: page.url(), contextualHelp: true, continuousLabQueue: true, mobileOverflow: false }))
} finally {
  await browser.close()
}
